# Generated by Django 6.0.3 on 2026-03-12 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Brief description of the expense.', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount in currency format.', max_digits=10)),
                ('category', models.CharField(help_text='Category of the expense (e.g., Food, Travel, Utilities).', max_length=100)),
                ('date', models.DateField(help_text='Date when the expense was incurred.')),
                ('notes', models.TextField(blank=True, help_text='Optional notes or comments about the expense.', null=True)),
                ('user', models.ForeignKey(help_text='The user associated with this expense.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
